### ISSUE TITLE
Stats and playtime tracking

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#49]
Allow to make some stats on how many hours people tend to play the game.
- [ ] Work out valid privacy policy
- [x] Add time tracking
- [x] Establish api endpoint to send stats to
- [ ] Add checkbox to options to disable

---

From stream 2016-08-10

**Comment by jhovgaard** [comment]
Partially done.

**Comment by InDieTasten** [comment]
Wait. What does

> Partially done.

even mean?

**Comment by jhovgaard** [comment]
@InDieTasten Sorry, should have elaborated. I'm going to remove tracking in the final version, so the current tracking is only for the beta.

The stats I use today will automatically be tracked by Steamworks (playtime, archievements and so on).

**Comment by InDieTasten** [comment]
Ok. Got it!
